### ISSUE TITLE
Duplicate product Number (PRN)

### ISSUE THREAD

**Issue by webpalnp** [act360/fonepay-for-woocommerce#1]
Getting this error when the first payment is failed and the customer tries to pay using Fonepay again.

**Comment by act360** [comment]
Thank you @webpalnp for reporting the issue.
Currently, PRN is woocommerce order id which doesn't change while trying to make payment again.
And fonepay needs PRN to be unique which is failing the payment. It doesn't discard the old PRN even if the payment fails.

We'll work on the solution. At the mean time, please feel free to contribute if you can.

Regards,

**Comment by lijnam** [comment]
should be fixed with  #2

**Comment by act360** [comment]
@webpalnp this has been solved in this repo and an update in wordpress repository plugin will be available this week.

Thanks.
