### ISSUE TITLE
Update with new V2 Doc

### ISSUE THREAD

**Issue by lijnam** [act360/fonepay-for-woocommerce#5]
- [ ] Update PRN value to be less than 20 char
- [ ] Update Response Validation

[20211112_164145.pdf](https://github.com/act360/fonepay-for-woocommerce/files/7574322/20211112_164145.pdf)

**Comment by lijnam** [comment]
@act360 is anyone available to update it?

**Comment by act360** [comment]
Hi,

Thank you for your commit.

We will update this soon.

Thank You.

**Comment by act360** [comment]
Hi @lijnam ,

The updated version will available here and in WordPress repository next week.

Thank you,

**Comment by act360** [comment]
Hi @lijnam,

The update for plugin is available in [WordPress repository](https://wordpress.org/plugins/integrate-fonepay-in-woocommerce/) as well as in this repository.

Please let us know if you face any error.

Thanks,
