### ISSUE TITLE
After the payment is successful, the website just keep on loading.

### ISSUE THREAD

**Issue by jukotberg** [act360/fonepay-for-woocommerce#7]
While making the payment through the QR code, The payment is completed but it is not redirecting to the order complete page. It just keeps on loading.

The request sent to the fonepay is:
https://clientapi.fonepay.com/api/merchantRequest?PID=1010101010101010&MD=P&AMT=150.00&CRN=NPR&DT=04/08/2024&R1=Product Name&R2=https://example.com&DV=2413558ee119a632a0976bce918b6b1f4104864f4cd3fb11c5aa030d1012ce4ee42af224b217485bb31b3352b89c91889c64fd568558220390bb8706a1864a90&PRN=wc_order_KpGQNygmPgEgm&RU=https://example.com/wc-api/WC_Gateway_Fonepay/

After the payment is successful, the response is:
https://example.com/wc-api/WC_Gateway_Fonepay/?PRN=wc_order_KpGQNygmPgEgm&PID=1010101010101010&PS=true&RC=successful&DV=2413558ee119a632a0976bce918b6b1f4104864f4cd3fb11c5aa030d1012ce4ee42af224b217485bb31b3352b89c91889c64fd568558220390bb8706a1864a90&UID=109011001&BC=NICENPKA&INI=9000000001&P_AMT=150.0&R_AMT=150.00

**Comment by act360** [comment]
Hi @jukotberg ,

Is it possible for you provide a snippet from log file of this transaction?

Thank you

**Comment by developerpsingh** [comment]
Which snippet is required? 

Please explain or to escalate the matter faster can we schedule a Google meet so we can demonstrate the bug.

**Comment by act360** [comment]
Hi @developerpsingh,

You can find the log path in WooCommerce > Settings > Payments > Fonepay > Advanced options.
![WooCommerce-settings-fonepay](https://github.com/act360/fonepay-for-woocommerce/assets/26865057/99ca5a13-671c-4d5f-b065-fd7602862b1b)

Thank you,

**Comment by developerpsingh** [comment]
I noticed the logs have confidential information which is not likely to be shared here, Can you please provide your email address or any alternative way to share the log file with you

**Comment by act360** [comment]
Hi @developerpsingh,

Please be advised that we are neither linked with Fonepay in anyway nor we are dedicated support partner for the Fonepay.

If you're still willing to share the information, please mail the log to developers@act360.com.np . You can obfuscate the confidential info like txn id, etc.

PS: Also this communication doesn't ensure that the issue will be looked into or resolved immediately.

Thank you,

**Comment by developerpsingh** [comment]
The required log file is shared with you on the email developers@act360.com.np please check and confirm.
