### ISSUE TITLE
Issue with Successful Transaction Redirect in Fonepay Plugin Integration

### ISSUE THREAD

**Issue by ResonanceHybrid** [act360/fonepay-for-woocommerce#8]
I recently integrated the Fonepay plugin on my WooCommerce website, [meesaa.com](http://meesaa.com/). While the integration generally works well, I have encountered an issue where, after a successful transaction, the process gets stuck on an API URL.

Stuck On URL = "https://meesaa.com/wc-api/WC_Gateway_Fonepay/?PRN=wc_order_a4kGIr5ADKMpo&PID=2222100016052033&PS=true&RC=successful&DV=D547405F0AE2B82CD3E1B99C74263B77109124FC5FFA2E991962BAA9EB46E3A3C1E61EE4C79B07450C3940F857D05CCEBF9D07D9911EA1EE23A804642BBB30E7&UID=310701665&BC=NARBNPKA&INI=9813672903&P_AMT=1.0&R_AMT=1"

but when I tap on the same URL after a few hours the URL redirection works well, but as soon as the transaction gets successful there's just a blank screen.

**Comment by act360** [comment]
Hi,

Was the payment done by QR scan or internet/mobile banking?

**Comment by ResonanceHybrid** [comment]
The payment was done by QR

**Comment by act360** [comment]
This is a known issue but we do not have enough information from FonePay to resolve it at the moment.

Mobile/Internet banking should work without issues. Please let us know if not.

We'll publish the updated version when we have the information to fix the issue.

Thank you,
