### ISSUE TITLE
Accept INR- UPI payments

### ISSUE THREAD

**Issue by lijnam** [act360/fonepay-for-woocommerce#9]
As Fonepay have UPI enabled, please enable UPI payments
Thanks :)

**Comment by act360** [comment]
Thank you for letting us know.

We have requested for latest documentation. We'll let you know if plugin is updated to incorporate the same in near future.

**Comment by act360** [comment]
Hi there,

Based on the documentation we received, there's nothing that caters UPI currently.

Thank you,
